/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const CustomerProfile = IDL.Record({
  'createdAt' : Timestamp,
  'businessName' : IDL.Text,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'customerId' : IDL.Nat,
});
export const ServiceRequest = IDL.Record({
  'serviceName' : IDL.Text,
  'requestId' : IDL.Nat,
  'createdAt' : Timestamp,
  'notes' : IDL.Text,
  'customerId' : IDL.Nat,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'author' : IDL.Text,
  'updatedAt' : Timestamp,
  'excerpt' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ConsultationRequest = IDL.Record({
  'id' : IDL.Text,
  'cityState' : IDL.Text,
  'fullName' : IDL.Text,
  'utmSource' : IDL.Opt(IDL.Text),
  'selectedService' : IDL.Text,
  'timestamp' : Timestamp,
  'phoneNumber' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const GrievanceCategory = IDL.Variant({
  'safety' : IDL.Null,
  'other' : IDL.Null,
  'noise' : IDL.Null,
  'maintenance' : IDL.Null,
  'cleanliness' : IDL.Null,
});
export const Grievance = IDL.Record({
  'id' : IDL.Text,
  'referenceNumber' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'category' : GrievanceCategory,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerProfile)], ['query']),
  'getAllServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerProfile' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CustomerProfile)],
      ['query'],
    ),
  'getServiceRequestsByCustomer' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listConsultationRequests' : IDL.Func([], [IDL.Vec(ConsultationRequest)], []),
  'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
  'listGrievances' : IDL.Func([], [IDL.Vec(Grievance)], []),
  'loginCustomer' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : CustomerProfile, 'err' : IDL.Text })],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'signUpWithInternetIdentity' : IDL.Func([], [IDL.Principal], []),
  'signupCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'submitConsultationRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitGrievance' : IDL.Func(
      [IDL.Text, IDL.Text, GrievanceCategory, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitServiceRequest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const CustomerProfile = IDL.Record({
    'createdAt' : Timestamp,
    'businessName' : IDL.Text,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'customerId' : IDL.Nat,
  });
  const ServiceRequest = IDL.Record({
    'serviceName' : IDL.Text,
    'requestId' : IDL.Nat,
    'createdAt' : Timestamp,
    'notes' : IDL.Text,
    'customerId' : IDL.Nat,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'author' : IDL.Text,
    'updatedAt' : Timestamp,
    'excerpt' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ConsultationRequest = IDL.Record({
    'id' : IDL.Text,
    'cityState' : IDL.Text,
    'fullName' : IDL.Text,
    'utmSource' : IDL.Opt(IDL.Text),
    'selectedService' : IDL.Text,
    'timestamp' : Timestamp,
    'phoneNumber' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const GrievanceCategory = IDL.Variant({
    'safety' : IDL.Null,
    'other' : IDL.Null,
    'noise' : IDL.Null,
    'maintenance' : IDL.Null,
    'cleanliness' : IDL.Null,
  });
  const Grievance = IDL.Record({
    'id' : IDL.Text,
    'referenceNumber' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'category' : GrievanceCategory,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerProfile)], ['query']),
    'getAllServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getBlogPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerProfile' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getServiceRequestsByCustomer' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listConsultationRequests' : IDL.Func(
        [],
        [IDL.Vec(ConsultationRequest)],
        [],
      ),
    'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
    'listGrievances' : IDL.Func([], [IDL.Vec(Grievance)], []),
    'loginCustomer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : CustomerProfile, 'err' : IDL.Text })],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'signUpWithInternetIdentity' : IDL.Func([], [IDL.Principal], []),
    'signupCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'submitConsultationRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitGrievance' : IDL.Func(
        [IDL.Text, IDL.Text, GrievanceCategory, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitServiceRequest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };