/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'author' : string,
  'updatedAt' : Timestamp,
  'excerpt' : string,
}
export interface ConsultationRequest {
  'id' : string,
  'cityState' : string,
  'fullName' : string,
  'utmSource' : [] | [string],
  'selectedService' : string,
  'timestamp' : Timestamp,
  'phoneNumber' : string,
}
export interface ContactMessage {
  'id' : string,
  'subject' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export interface Grievance {
  'id' : string,
  'referenceNumber' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'email' : string,
  'category' : GrievanceCategory,
}
export type GrievanceCategory = { 'safety' : null } |
  { 'other' : null } |
  { 'noise' : null } |
  { 'maintenance' : null } |
  { 'cleanliness' : null };
export type Timestamp = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<[string, string, string, string], string>,
  'getBlogPost' : ActorMethod<[string], BlogPost>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listConsultationRequests' : ActorMethod<[], Array<ConsultationRequest>>,
  'listContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'listGrievances' : ActorMethod<[], Array<Grievance>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'signUpWithInternetIdentity' : ActorMethod<[], Principal>,
  'submitConsultationRequest' : ActorMethod<
    [string, string, string, string, [] | [string]],
    string
  >,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    string
  >,
  'submitGrievance' : ActorMethod<
    [string, string, GrievanceCategory, string],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];